class PaypalWebhooksService
  # BILLING.PLAN.CREATED  A billing plan is created.  Create billing plan
  # BILLING.PLAN.UPDATED  A billing plan is updated.  Update billing plan
  # BILLING.SUBSCRIPTION.CANCELLED  A billing agreement is canceled.  Cancel agreement
  # BILLING.SUBSCRIPTION.CREATED  A billing agreement is created. Create agreement
  # BILLING.SUBSCRIPTION.RE-ACTIVATED A billing agreement is re-activated.  Re-activate agreement
  # BILLING.SUBSCRIPTION.SUSPENDED  A billing agreement is suspended. Suspend agreement
  # BILLING.SUBSCRIPTION.UPDATED

  # FOR NOW, THE ONLY ONES THAT WE NEED TO KNOW ABOUT ARE BILLING.SUBSCRIPTION.CANCELLED
  # AND BILLING.SUBSCRIPTION.SUSPENDED

  # FOR GENERAL PAYMENTS, PAYMENT.SALE.COMPLETED AND PAYMENT.SALE.DENIED LET US
  # KNOW OF SUCCESSFULL AND FAILED RECURRING PAYMENTS. WE CAN USE THESE TO GENERATE
  # INVOICES AND UPDATE THE SUBSCRIPTION OBJECT'S STATE AND NEXT BILLING DATE, ETC...
  # IF A SUBSCRIPTION NEEDS TO BE CANCELLED OR MARKED 'ERRORED', THEN THIS IS WHERE
  # WE'LL DO IT
end
