require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - db/**/*
    - Gemfile
    - vendor/**/*
    - config/environments/*
    - bin/**/*

Rails:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: exploded

Style/HashEachMethods:
   Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Naming/FileName:
  Enabled: false

Performance/Count:
  SafeAutoCorrect: false
