AllCops:
  Exclude:
    - db/**/*
    - Gemfile
    - vendor/**/*
    - config/environments/*
    - bin/**/*

Rails:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: exploded

Naming/FileName:
    Enabled: false

# Disables "Missing top-level class documentation comment" warning
Documentation:
  Enabled: false
