version: '3'
services:
  db:
    environment:
      POSTGRES_DB: learnsignal_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass2015
      PGDATA: /pgdata
    env_file:
      - local_env.yml
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/version1
    ports:
      - 5432:5432
    depends_on:
      - db
      - sidekiq
      - redis

  redis:
    image: redis:4.0.5-alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/version1
    env_file:
      - .env  

 