default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: db/learnsignal_development

test:
  <<: *default
  database: db/learnsignal_v3_test

staging:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
