SECRET_KEY_BASE: 'replace_me'

FREE_TRIAL_DAYS: "7"
FREE_TRIAL_LIMIT_IN_SECONDS: "2700"

# Personal Email
LEARNSIGNAL_V2_SERVER_EMAIL_SMTP: smtp.mandrillapp.com
LEARNSIGNAL_V3_SERVER_EMAIL_ADDRESS: Signal Education
LEARNSIGNAL_V3_SERVER_EMAIL_DOMAIN: 'localhost:3000'
#learnsignal_v3_server_email_domain: learnsignal.com
LEARNSIGNAL_V3_SERVER_EMAIL_PASSWORD: uKK_pGl-9PK54IhUzx5Ajg
#learnsignal_v3_server_email_password: ChlsjrE7dGKKQLAWd3vwyw

# Mandrill
LEARNSIGNAL_MANDRILL_API_KEY: uKK_pGl-9PK54IhUzx5Ajg

# Stripe
LEARNSIGNAL_V3_STRIPE_API_KEY: sk_test_wEVy0Tzgi3HEzoeJk4t340vI
LEARNSIGNAL_V3_STRIPE_PUBLIC_KEY: pk_test_QNs2TrDsJ5o0IyesV7U2THq5
LEARNSIGNAL_V3_STRIPE_LIVE_MODE: test


# AWS S3
LEARNSIGNAL3_BUCKET_NAME: replace_me_with_s3_bucket_name #learnsignal3-dev-james
LEARNSIGNAL3_S3_ACCESS_KEY_ID: replace_me_with_s3_accesskey #AKIAJOFRK7DP5CMUXHYQ
LEARNSIGNAL3_S3_SECRET_ACCESS_KEY: replace_me_with_s3_secret_key #3cEZfgKnxtDj/2/nIgMQkSAMi7YoXn1L1C1CUJR+

# Intercom
INTERCOM_APP_ID: j2w4wgd5
INTERCOM_API_KEY: b1a9b2231634d4050aad1f986df1e6412f2b6614
INTERCOM_SECRET_KEY: w-tlJqQNTRYRXL_jcJoE3DoLLkMpKMHgkGvivqbk
#Test Access Token
INTERCOM_ACCESS_TOKEN: dG9rOjk1YWI5ZWY1XzY1N2NfNDA4Nl9hZWQ3X2UxNjhiMzc0N2ViZjoxOjA=


# MailChimp
LEARNSIGNAL_MAILCHIMP_API_KEY: d2eee250b68117a0ab90b6c03c0ca9d9-us3
LEARNSIGNAL_MAILCHIMP_LIST_ID: 866fa91d62  #Test List


# Vimeo Api
LEARNSIGNAL_VIMEO_API_KEY: a3b067f4c5605adb58d0fc1f599d76a6

# Pointpin Api
LEARNSIGNAL_POINTPIN_API_KEY: b36dbb3d-b657-44fb-83fd-84519a7c0520

# Google Api
LEARNSIGNAL_GOOGLE_API_KEY: AIzaSyAy_pLHbNFWC9aT-PGrkEv7fyfdiDv2ECk



# AWS Load Balancers
# For each configuration we have to list all load balancer IPs in
# order to get real request IP. Namely ActionDispatch::RemoteIp
# middleware removes all IPs from ActionDispatch::RemoteIp::TRUSTED_PROXIES
# leaving real request IP. If AWS load balancers are not added to
# this array instead of user's IP address we will get load balancer's
# IP addres.
#
# Format of values listed here are IP addresses (optionally with network
# prefix length) separated by commas. In environemnts/<configuration>.rb
# file we split this value on comma char and add each address is added to
# the array of TRUSTED_PROXIES.
#
# Sample of value (first address is given with network prefix length 20,
# and second is single IP).
#
# 172.31.0.0/20,54.154.194.123
#
# Configured value for load balancer's IP address with network
# prefix length for can be seen from Availability Zones list
# for each load balancer in AWS console (go to Load Balancers, select
# load balancer and in bottom table all availability zones are listed).
AWS_LOAD_BALANCERS: 172.31.16.0/20


DB_ADAPTER: postgresql
DB_HOSTNAME: localhost
DB_USERNAME:
DB_PASSWORD:
DB_NAME: postgresql

#Redis DB
#when "test"
  #redis_host = ENV["REDIS_TEST_HOST"]
  #redis_host_port = ENV["REDIS_TEST_HOST_PORT"]
#when "development"
  #redis_host = ENV["REDIS_DEVELOPMENT_HOST"]
  #redis_host_port = ENV["REDIS_DEVELOPMENT_HOST_PORT"]