DB_ADAPTER: 
DB_HOSTNAME: 
DB_USERNAME:
DB_PASSWORD:
DB_NAME: 


SECRET_KEY_BASE: 
FREE_TRIAL_LIMIT_IN_SECONDS: 
# Personal Email
LEARNSIGNAL_V2_SERVER_EMAIL_SMTP: 
LEARNSIGNAL_V3_SERVER_EMAIL_ADDRESS: 
LEARNSIGNAL_V3_SERVER_EMAIL_DOMAIN: 
#learnsignal_v3_server_email_domain: learnsignal.com
LEARNSIGNAL_V3_SERVER_EMAIL_PASSWORD: 
#learnsignal_v3_server_email_password: ChlsjrE7dGKKQLAWd3vwyw
# Mandrill
#learnsignal_mandrill_api_key: Pf3KNRuWBG7Ytfg-pn9fVg  production
#learnsignal_mandrill_api_key: ChlsjrE7dGKKQLAWd3vwyw  #staging
LEARNSIGNAL_MANDRILL_API_KEY: 
# Stripe
LEARNSIGNAL_V3_STRIPE_API_KEY: 
LEARNSIGNAL_V3_STRIPE_PUBLIC_KEY: 
LEARNSIGNAL_V3_STRIPE_LIVE_MODE: 
# AWS S3
LEARNSIGNAL3_BUCKET_NAME: 
LEARNSIGNAL3_S3_ACCESS_KEY_ID: 
LEARNSIGNAL3_S3_SECRET_ACCESS_KEY: 
# Intercom
INTERCOM_APP_ID: 
#IntercomAppID: a81yx184 # live
INTERCOM_API_KEY: 
#INTERCOM_SECRET_KEY: rx_JkvkOGY6n0NxwjrvXoUwEsKtT1x2czo46OnK_
INTERCOM_SECRET_KEY: 
#Live Access Token
#INTERCOM_ACCESS_TOKEN: dG9rOjYzMjcyZGE2XzBhNWRfNDkwZF84ODZlX2I5YWY0NTc1MzM3NDoxOjA=
#Test Access Token
INTERCOM_ACCESS_TOKEN: 
# MailChimp
LEARNSIGNAL_MAILCHIMP_API_KEY: 
#learnsignal_mailchimp_list_id: dcac53aa7d #Production list
LEARNSIGNAL_MAILCHIMP_LIST_ID:   #Test List
# Wistia Data Api
LEARNSIGNAL_WISTIA_API_KEY: 
# Vimeo Api
LEARNSIGNAL_VIMEO_API_KEY: 
# Pointpin Api
LEARNSIGNAL_POINTPIN_API_KEY: 
# Zendesk Api
LEARNSIGNAL_ZENDESK_API_KEY: 
# AWS Load Balancers
# For each configuration we have to list all load balancer IPs in
# order to get real request IP. Namely ActionDispatch::RemoteIp
# middleware removes all IPs from ActionDispatch::RemoteIp::TRUSTED_PROXIES
# leaving real request IP. If AWS load balancers are not added to
# this array instead of user's IP address we will get load balancer's
# IP addres.
#
# Format of values listed here are IP addresses (optionally with network
# prefix length) separated by commas. In environemnts/<configuration>.rb
# file we split this value on comma char and add each address is added to
# the array of TRUSTED_PROXIES.
#
# Sample of value (first address is given with network prefix length 20,
# and second is single IP).
#
# 172.31.0.0/20,54.154.194.123
#
# Configured value for load balancer's IP address with network
# prefix length for can be seen from Availability Zones list
# for each load balancer in AWS console (go to Load Balancers, select
# load balancer and in bottom table all availability zones are listed).
AWS_LOAD_BALANCERS: 
# Google Api
LEARNSIGNAL_GOOGLE_API_KEY: 

#Redis DB
#when "test"
  #redis_host = ENV["REDIS_TEST_HOST"]
  #redis_host_port = ENV["REDIS_TEST_HOST_PORT"]
#when "development"
  #redis_host = ENV["REDIS_DEVELOPMENT_HOST"]
  #redis_host_port = ENV["REDIS_DEVELOPMENT_HOST_PORT"]




