# This is an example of the content that each developer and
# server should have in the application.yml file.
# ---------------------------------------------------------
# Operated by the figaro gem.

# General
SECRET_KEY_BASE: 128-character-code
free_trial_days: "7"
free_trial_limit_in_seconds: "12000"

# Email sending
learnsignal_v3_server_email_address: 'some-account@gmail.com'
learnsignal_v3_server_email_password: 'password-for-gmail-account'

# Stripe
learnsignal_v3_stripe_public_key: pk_test_some-code-goes-here
learnsignal_v3_stripe_api_key: sk_test_some-code-goes-here
learnsignal_v3_stripe_live_mode: test # live

# AWS
LEARNSIGNAL3_BUCKET_NAME: learnsignal3-BUCKET-NAME
LEARNSIGNAL3_S3_ACCESS_KEY_ID: 20-character-code
LEARNSIGNAL3_S3_SECRET_ACCESS_KEY: 40-character-code

# Intercom
intercom_app_id: 8-char-code

# Mandrill
learnsignal_mandrill_api_key: uKK_pGl-9PK54IhUzx5Ajg

# AWS Load Balancers
# For each configuration we have to list all load balancer IPs in
# order to get real request IP. Namely ActionDispatch::RemoteIp
# middleware removes all IPs from ActionDispatch::RemoteIp::TRUSTED_PROXIES
# leaving real request IP. If AWS load balancers are not added to
# this array instead of user's IP address we will get load balancer's
# IP addres.
#
# Format of values listed here are IP addresses (optionally with network
# prefix length) separated by commas. In environemnts/<configuration>.rb
# file we split this value on comma char and add each address is added to
# the array of TRUSTED_PROXIES.
#
# Sample of value (first address is given with network prefix length 20,
# and second is single IP).
#
# 172.31.0.0/20,54.154.194.123
#
# Configured value for load balancer's IP address with network
# prefix length for can be seen from Availability Zones list
# for each load balancer in AWS console (go to Load Balancers, select
# load balancer and in bottom table all availability zones are listed).
aws_load_balancers: aws_load_balancers_ips_go_here

# Pointpin Api
learnsignal_pointpin_api_key: b36dbb3d-b657-44fb-83fd-84519a7c0520
