# This is an example of the content that each developer and
# server should have in the application.yml file.
# ---------------------------------------------------------
# Operated by the figaro gem.

# General
SECRET_KEY_BASE: 128-character-code
free_trial_days: "7"

# Email sending
learnsignal_v3_server_email_address: 'some-account@gmail.com'
learnsignal_v3_server_email_password: 'password-for-gmail-account'

# Stripe
learnsignal_v3_stripe_public_key: pk_test_some-code-goes-here
learnsignal_v3_stripe_api_key: sk_test_some-code-goes-here
learnsignal_v3_stripe_live_mode: test # live

# AWS
LEARNSIGNAL3_BUCKET_NAME: learnsignal3-BUCKET-NAME
LEARNSIGNAL3_S3_ACCESS_KEY_ID: 20-character-code
LEARNSIGNAL3_S3_SECRET_ACCESS_KEY: 40-character-code

# Intercom
intercom_app_id: 8-char-code

# MixPanel
mixpanel_key: mixpanel_api_key_goes_here

# Mandrill
learnsignal_mandrill_api_key: mandrill_api_key_goes_here
